source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'Feeds' do
    pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
    pod 'QMUIKit'
    pod 'ReactiveObjC'
    pod 'YTKNetwork'
    pod 'YTKKeyValueStore'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'TPKeyboardAvoiding'
    #    pod 'SDCycleScrollView','~> 1.75'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'BlocksKit'
end
